import { createStitches } from "@stitches/react";
import * as Colors from "colorcrafts";

export const { createTheme, css, getCssText, globalCss, keyframes, styled } =
  createStitches({
    theme: {
      colors: {
        primary: "#111111",
        ...Colors.Amber,
        ...Colors.Aquamarine,
        ...Colors.Black,
        ...Colors.Blue,
        ...Colors.Blue,
        ...Colors.Citrus,
        ...Colors.Cyan,
        ...Colors.Emerald,
        ...Colors.ForestGreen,
        ...Colors.Fuchsia,
        ...Colors.Gray,
        ...Colors.Green,
        ...Colors.Indigo,
        ...Colors.Lime,
        ...Colors.Neutral,
        ...Colors.Orange,
        ...Colors.Pink,
        ...Colors.Purple,
        ...Colors.Red,
        ...Colors.Rose,
        ...Colors.Rusty,
        ...Colors.Sky,
        ...Colors.Slate,
        ...Colors.Stone,
        ...Colors.Teal,
        ...Colors.Violet,
        ...Colors.White,
        ...Colors.Yellow,
        ...Colors.Zinc,
      },
      fonts: {
        sans: "Outfit, sans-serif",
        mono: "Cascadia Code, monospace",
      },
      fontSizes: {
        "text-xs": "0.75rem",
        "text-sm": "0.875rem",
        "text-base": "1rem",
        "text-lg": "1.125rem",
        "text-xl": "1.25rem",
        "text-2xl": "1.5rem",
        "text-3xl": "1.875rem",
        "text-4xl": "2.25rem",
        "text-5xl": "3rem",
        "text-6xl": "4rem",
      },
      sizes: {
        xss: "432px",
        xs: "576px",
        sm: "640px",
        md: "768px",
        lg: "992px",
        xl: "1100px",
      },
    },
    media: {
      xss: "(min-width: 432px)",
      xs: "(min-width: 576px)",
      sm: "(min-width: 640px)",
      md: "(min-width: 768px)",
      lg: "(min-width: 992px)",
      xl: "(min-width: 1100px)",
    },
  });
